In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings('ignore')

In [3]:
x, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=1)
x, y

(array([[-2.04582165, -0.13791624, -0.08071423, ...,  2.48194524,
          0.74236675,  0.23154789],
        [-0.98726024,  1.30120189,  2.37734888, ...,  0.55445754,
         -0.21892143, -0.37608578],
        [ 0.57335921,  0.09375582,  0.4662521 , ..., -0.6088508 ,
          0.79903499, -0.17121177],
        ...,
        [-0.70737159,  1.07650943,  0.58510456, ..., -1.51337602,
          0.90239871, -0.69230951],
        [-0.20706849,  1.17319848, -1.94478665, ..., -0.32820676,
          1.5711921 ,  1.14877729],
        [-2.16769231, -2.54871672,  2.89359255, ...,  0.71535366,
          0.34329241,  1.07350284]]),
 array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
   

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=1)
x_train.shape, y_train.shape

((670, 20), (670,))

In [5]:
classifier = AdaBoostClassifier()
classifier

AdaBoostClassifier()

In [6]:
classifier.fit(x_train, y_train)

AdaBoostClassifier()

In [7]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,

In [8]:
print(f"Accuracy score {accuracy_score(y_test, y_pred)}")
print(f"Classification report : \n{classification_report(y_test, y_pred)}")

Accuracy score 0.8090909090909091
Classification report : 
              precision    recall  f1-score   support

           0       0.78      0.82      0.80       154
           1       0.83      0.80      0.82       176

    accuracy                           0.81       330
   macro avg       0.81      0.81      0.81       330
weighted avg       0.81      0.81      0.81       330



In [11]:
params = {
    'n_estimators' : [50,100,200,500,400,250],
    'learning_rate' : [0.001,0.1,1,1.5,2,2.5],
    'algorithm' : ['SAMME.R','SAMME']
}

In [12]:
ada = AdaBoostClassifier()
grid = GridSearchCV(estimator=ada, param_grid=params, verbose=3, cv=5)
grid

GridSearchCV(cv=5, estimator=AdaBoostClassifier(),
             param_grid={'algorithm': ['SAMME.R', 'SAMME'],
                         'learning_rate': [0.001, 0.1, 1, 1.5, 2, 2.5],
                         'n_estimators': [50, 100, 200, 500, 400, 250]},
             verbose=3)

In [13]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits
[CV 1/5] END algorithm=SAMME.R, learning_rate=0.001, n_estimators=50;, score=0.881 total time=   0.1s
[CV 2/5] END algorithm=SAMME.R, learning_rate=0.001, n_estimators=50;, score=0.903 total time=   0.2s
[CV 3/5] END algorithm=SAMME.R, learning_rate=0.001, n_estimators=50;, score=0.843 total time=   0.2s
[CV 4/5] END algorithm=SAMME.R, learning_rate=0.001, n_estimators=50;, score=0.813 total time=   0.3s
[CV 5/5] END algorithm=SAMME.R, learning_rate=0.001, n_estimators=50;, score=0.813 total time=   0.2s
[CV 1/5] END algorithm=SAMME.R, learning_rate=0.001, n_estimators=100;, score=0.881 total time=   0.5s
[CV 2/5] END algorithm=SAMME.R, learning_rate=0.001, n_estimators=100;, score=0.903 total time=   0.4s
[CV 3/5] END algorithm=SAMME.R, learning_rate=0.001, n_estimators=100;, score=0.843 total time=   0.4s
[CV 4/5] END algorithm=SAMME.R, learning_rate=0.001, n_estimators=100;, score=0.813 total time=   0.4s
[CV 5/5] END alg

GridSearchCV(cv=5, estimator=AdaBoostClassifier(),
             param_grid={'algorithm': ['SAMME.R', 'SAMME'],
                         'learning_rate': [0.001, 0.1, 1, 1.5, 2, 2.5],
                         'n_estimators': [50, 100, 200, 500, 400, 250]},
             verbose=3)

In [14]:
grid.best_params_

{'algorithm': 'SAMME', 'learning_rate': 0.1, 'n_estimators': 500}

In [15]:
grid.best_score_

np.float64(0.8656716417910447)

In [16]:
best_model = grid.best_estimator_
best_model

AdaBoostClassifier(algorithm='SAMME', learning_rate=0.1, n_estimators=500)

In [17]:
y_pred = best_model.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,

In [18]:
accuracy_score(y_test, y_pred)

0.8484848484848485