In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [6]:
from sklearn.datasets import make_regression
x, y = make_regression(n_samples=1000, n_features=10, noise=0.1, random_state=1)
x, y

(array([[-1.24634541, -2.3575232 ,  0.60972409, ..., -1.25935848,
         -0.11048061,  0.46983129],
        [-0.68085157, -1.06787658,  0.57296273, ..., -0.01781755,
          0.45794708, -0.6001388 ],
        [-0.14894123,  1.16533544, -0.63259014, ...,  1.89716069,
         -0.20984695, -1.38139115],
        ...,
        [ 1.32960903, -1.08278525,  0.44347873, ..., -0.48363166,
          0.01880501,  0.56264832],
        [ 1.03703898,  0.67261975,  1.00568668, ...,  0.61472628,
          0.35356722, -0.34898419],
        [ 0.438562  ,  0.92781985,  0.72667997, ..., -1.09330391,
         -0.37195994,  0.22445073]]),
 array([-1.29703788e+02, -1.80999622e+01, -2.48373532e+02, -5.47790773e+01,
         2.53389312e+01,  1.64353500e+01, -1.62379961e+02,  8.68801965e+01,
        -3.03384035e+01, -1.99726617e+02, -1.13506241e+02, -1.90063912e+02,
        -1.87538897e+02,  1.72228819e+02,  6.16386076e+01, -3.56835616e+02,
         8.24251916e+01,  1.61358017e+02,  1.52957393e+02,  5.0042422

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
x_train.shape, y_train.shape

((800, 10), (800,))

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [12]:
lr_reg = LinearRegression()
dt_reg = DecisionTreeRegressor()
svm_reg = SVR()

In [14]:
from sklearn.ensemble import VotingRegressor
ensemble_reg = VotingRegressor(estimators=[('Linear Regression',lr_reg), ('Decision Tree Regressor',dt_reg),('Support Vector Regressor',svm_reg)])
ensemble_reg

VotingRegressor(estimators=[('Linear Regression', LinearRegression()),
                            ('Decision Tree Regressor',
                             DecisionTreeRegressor()),
                            ('Support Vector Regressor', SVR())])

In [15]:
ensemble_reg.fit(x_train, y_train)

VotingRegressor(estimators=[('Linear Regression', LinearRegression()),
                            ('Decision Tree Regressor',
                             DecisionTreeRegressor()),
                            ('Support Vector Regressor', SVR())])

In [16]:
y_pred = ensemble_reg.predict(x_test)
y_pred

array([ 3.20205380e+01,  1.51049760e+01, -2.75738203e+01, -2.81733926e+01,
        3.29414682e+02,  2.32046260e+02,  2.57880212e+01, -6.32665525e+01,
       -7.85569989e+01, -5.02719324e+01, -7.50517852e+01,  3.40919199e+01,
       -4.24767832e+01, -1.08174454e+02, -2.01100801e+02, -9.64809116e+01,
       -1.85913229e+02, -1.19754763e+02, -2.41864286e+01, -1.51210440e+02,
       -3.14014082e+01, -8.81493831e+01,  2.01736338e+02, -1.14694162e+02,
        7.01370133e+01,  1.34345168e+02,  1.60149553e+02,  2.93514977e+01,
       -2.88607916e+01,  9.04539659e+01,  5.81961125e+01,  1.40293153e+02,
        7.46206555e+01,  1.95367538e+02,  7.71432992e+01,  6.86211973e+01,
        4.59080194e+01, -2.74375855e+02, -1.29938087e+02, -4.87749793e+01,
       -1.36628407e+01, -5.25815609e+01,  8.01703622e+01, -6.62623825e+01,
        6.78500467e+01,  6.67969090e+00,  1.17408175e+02, -6.62105839e+01,
        1.06439654e+02, -2.06803772e+02,  1.44847673e+02,  2.44860522e+02,
       -1.57375656e+02,  

In [19]:
ensemble_reg.named_estimators_

{'Linear Regression': LinearRegression(),
 'Decision Tree Regressor': DecisionTreeRegressor(),
 'Support Vector Regressor': SVR()}

In [20]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7969667077816435

In [24]:
regressors = [lr_reg, dt_reg, svm_reg]
for reg in regressors:
    reg.fit(x_train, y_train)
    y_pred = reg.predict(x_test)
    print(f"Accuracy score by {reg} is {r2_score(y_test, y_pred)}")
    print("================================================================\n")

Accuracy score by LinearRegression() is 0.9999997305184231

Accuracy score by DecisionTreeRegressor() is 0.5775022283396217

Accuracy score by SVR() is 0.1851630606854321

