In [53]:
#Data Encoding>> converting categorical columns to numeric
# Nomianl/OHE
# Label and ordinal
# Target Guided Ordinal encoding

In [54]:
# Nominal OHE>> binary vectors for each category
# Single Married Relationship
# Single> [1,0,0]
# Married> [0,1,0]
# Relationship> [0,0,1]

In [55]:
import pandas as pd
import numpy as np

In [56]:
from sklearn.preprocessing import OneHotEncoder

In [57]:
df=pd.DataFrame({'status':['Single','Married','Single','Relationship','Married','Single']})
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [58]:
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['status']]).toarray()
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [59]:
encoder.get_feature_names_out()

array(['status_Married', 'status_Relationship', 'status_Single'],
      dtype=object)

In [60]:
df1=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
df1

status_Married  status_Relationship  status_Single
0             0.0                  0.0            1.0
1             1.0                  0.0            0.0
2             0.0                  0.0            1.0
3             0.0                  1.0            0.0
4             1.0                  0.0            0.0
5             0.0                  0.0            1.0

In [61]:
#New data
encoder.transform([['Single']]).toarray()

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [62]:
encoder.transform([['Married']]).toarray

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


<bound method _cs_matrix.toarray of <1x3 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>>

In [63]:
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [64]:
df1

status_Married  status_Relationship  status_Single
0             0.0                  0.0            1.0
1             1.0                  0.0            0.0
2             0.0                  0.0            1.0
3             0.0                  1.0            0.0
4             1.0                  0.0            0.0
5             0.0                  0.0            1.0

In [65]:
final_df=pd.concat([df,df1],axis=1)
final_df

status  status_Married  status_Relationship  status_Single
0        Single             0.0                  0.0            1.0
1       Married             1.0                  0.0            0.0
2        Single             0.0                  0.0            1.0
3  Relationship             0.0                  1.0            0.0
4       Married             1.0                  0.0            0.0
5        Single             0.0                  0.0            1.0

In [66]:
final_df.drop(['status','status_Married'],axis=1,inplace=True)

In [67]:
final_df

status_Relationship  status_Single
0                  0.0            1.0
1                  0.0            0.0
2                  0.0            1.0
3                  1.0            0.0
4                  0.0            0.0
5                  0.0            1.0

In [68]:
pd.get_dummies(df['status'])

Married  Relationship  Single
0    False         False    True
1     True         False   False
2    False         False    True
3    False          True   False
4     True         False   False
5    False         False    True

In [69]:
pd.get_dummies(df['status'],drop_first=True)

Relationship  Single
0         False    True
1         False   False
2         False    True
3          True   False
4         False   False
5         False    True

In [70]:
pd.get_dummies(df['status'],drop_first=True,dtype='int')

Relationship  Single
0             0       1
1             0       0
2             0       1
3             1       0
4             0       0
5             0       1

In [71]:
import seaborn as sns

In [72]:
df_tips=sns.load_dataset('tips')

In [73]:
df_tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [74]:
df_tips.drop(['total_bill','sex','smoker','size'],axis=1,inplace=True)

In [75]:
df_tips

tip   day    time
0    1.01   Sun  Dinner
1    1.66   Sun  Dinner
2    3.50   Sun  Dinner
3    3.31   Sun  Dinner
4    3.61   Sun  Dinner
..    ...   ...     ...
239  5.92   Sat  Dinner
240  2.00   Sat  Dinner
241  2.00   Sat  Dinner
242  1.75   Sat  Dinner
243  3.00  Thur  Dinner

[244 rows x 3 columns]

In [76]:
df_tips.shape

(244, 3)

In [77]:
df_tips.day.unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [78]:
day_encoded=encoder.fit_transform(df_tips[['day']]).toarray()
day_encoded

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],


In [79]:
encoder.get_feature_names_out()

array(['day_Fri', 'day_Sat', 'day_Sun', 'day_Thur'], dtype=object)

In [80]:
df_tips1=pd.DataFrame(day_encoded,columns=encoder.get_feature_names_out())
df_tips1

day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [81]:
day_df=pd.concat([df_tips,df_tips1],axis=1)
day_df

tip   day    time  day_Fri  day_Sat  day_Sun  day_Thur
0    1.01   Sun  Dinner      0.0      0.0      1.0       0.0
1    1.66   Sun  Dinner      0.0      0.0      1.0       0.0
2    3.50   Sun  Dinner      0.0      0.0      1.0       0.0
3    3.31   Sun  Dinner      0.0      0.0      1.0       0.0
4    3.61   Sun  Dinner      0.0      0.0      1.0       0.0
..    ...   ...     ...      ...      ...      ...       ...
239  5.92   Sat  Dinner      0.0      1.0      0.0       0.0
240  2.00   Sat  Dinner      0.0      1.0      0.0       0.0
241  2.00   Sat  Dinner      0.0      1.0      0.0       0.0
242  1.75   Sat  Dinner      0.0      1.0      0.0       0.0
243  3.00  Thur  Dinner      0.0      0.0      0.0       1.0

[244 rows x 7 columns]

In [82]:
pd.get_dummies(df_tips['day'],dtype='int')

Thur  Fri  Sat  Sun
0       0    0    0    1
1       0    0    0    1
2       0    0    0    1
3       0    0    0    1
4       0    0    0    1
..    ...  ...  ...  ...
239     0    0    1    0
240     0    0    1    0
241     0    0    1    0
242     0    0    1    0
243     1    0    0    0

[244 rows x 4 columns]

In [83]:
#Label Encdoding>> assign unique label to each category
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [84]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [85]:
encoder.fit_transform(df[['status']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 2, 1, 0, 2])

In [86]:
# Ordinal Encoding
# school>1
# ug>2
# pg>3
# phd>4

In [87]:
from sklearn.preprocessing import OrdinalEncoder

In [88]:
df=pd.DataFrame({'qualification':['HS','PG','HS','UG','PHD','HS','PG']})
df

qualification
0            HS
1            PG
2            HS
3            UG
4           PHD
5            HS
6            PG

In [89]:
ordinal_encoder=OrdinalEncoder(categories=[['HS','UG','PG','PHD']])
ordinal_encoder

OrdinalEncoder(categories=[['HS', 'UG', 'PG', 'PHD']])

In [90]:
encoded=ordinal_encoder.fit_transform(df[['qualification']])
encoded

array([[0.],
       [2.],
       [0.],
       [1.],
       [3.],
       [0.],
       [2.]])

In [91]:
df.qualification.value_counts()

qualification
HS     3
PG     2
UG     1
PHD    1
Name: count, dtype: int64

In [92]:
 #Top 5/Top 10 approach>> atleast 70 or 80% of the categorical columns is captured

In [93]:
# Target Guided Ordinal Encoding
# Relation between target variables
# A lot of unique categories
# Replace with mean or median

In [94]:
df=pd.DataFrame({'time':['lunch','breakfast','breakfast','dinner','lunch','breakfast','dinner','breakfast','dinner','lunch'],'total_bill':[120,150,200,130,180,200,250,180,160,120]})
df

time  total_bill
0      lunch         120
1  breakfast         150
2  breakfast         200
3     dinner         130
4      lunch         180
5  breakfast         200
6     dinner         250
7  breakfast         180
8     dinner         160
9      lunch         120

In [95]:
mean_price=dict(df.groupby('time')['total_bill'].mean())
mean_price

{'breakfast': 182.5, 'dinner': 180.0, 'lunch': 140.0}

In [96]:
df['time_target_encoded']=df['time'].map(mean_price)
df

time  total_bill  time_target_encoded
0      lunch         120                140.0
1  breakfast         150                182.5
2  breakfast         200                182.5
3     dinner         130                180.0
4      lunch         180                140.0
5  breakfast         200                182.5
6     dinner         250                180.0
7  breakfast         180                182.5
8     dinner         160                180.0
9      lunch         120                140.0

In [97]:
tips_df=sns.load_dataset('tips')
tips_df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [98]:
tips_df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [99]:
tips_df.drop(['tip', 'sex', 'smoker', 'day', 'size'],axis=1,inplace=True)

In [100]:
tips_df

total_bill    time
0         16.99  Dinner
1         10.34  Dinner
2         21.01  Dinner
3         23.68  Dinner
4         24.59  Dinner
..          ...     ...
239       29.03  Dinner
240       27.18  Dinner
241       22.67  Dinner
242       17.82  Dinner
243       18.78  Dinner

[244 rows x 2 columns]

In [101]:
mean_bill=tips_df.groupby('time')['total_bill'].mean().to_dict()
mean_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [102]:
tips_df['time_target_encoded']=tips_df['time'].map(mean_bill)
tips_df

total_bill    time time_target_encoded
0         16.99  Dinner           20.797159
1         10.34  Dinner           20.797159
2         21.01  Dinner           20.797159
3         23.68  Dinner           20.797159
4         24.59  Dinner           20.797159
..          ...     ...                 ...
239       29.03  Dinner           20.797159
240       27.18  Dinner           20.797159
241       22.67  Dinner           20.797159
242       17.82  Dinner           20.797159
243       18.78  Dinner           20.797159

[244 rows x 3 columns]

In [103]:
df=sns.load_dataset('taxes')
df

ValueError: 'taxes' is not one of the example datasets.