In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [3]:
x, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)
x, y

(array([[ 2.56999479, -0.13019997,  3.16075093, ..., -1.93094078,
          3.26130366,  2.05692145],
        [ 0.34129317,  2.51321418, -0.80416572, ...,  6.24734437,
         -1.92769365,  2.9503149 ],
        [ 2.27539972,  3.36561455,  0.17164362, ...,  2.74693781,
          0.13492444,  2.00339547],
        ...,
        [ 0.5234359 ,  1.90466429,  0.93243365, ...,  1.53945231,
          1.90646166,  1.99458587],
        [ 1.33747921,  3.25859684,  0.78792366, ...,  5.18788314,
         -0.82071083,  3.51411431],
        [-0.98534299,  0.83919047,  2.5820803 , ...,  3.04705685,
          0.66885641,  3.32838496]]),
 array([1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
        1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
   

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
x_train.shape, y_train.shape

((800, 10), (800,))

In [5]:
model = LogisticRegression()
model

LogisticRegression()

In [6]:
model.fit(x_train,y_train)

LogisticRegression()

In [8]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1])

In [11]:
accuracy_score(y_test,y_pred)

0.825

In [58]:
#Grid Search Cv>> take all possible values
from sklearn.model_selection import GridSearchCV
params = {
    'penalty':['l1','l2','elasticnet'],
    'C':[0.1,0.2,0.21211,0.15,0.25,0.3,1,2,3,4,5,10,20]
}

In [59]:
clf = GridSearchCV(estimator=model, param_grid=params, cv=5, verbose=3)
clf

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.1, 0.2, 0.21211, 0.15, 0.25, 0.3, 1, 2, 3, 4,
                               5, 10, 20],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             verbose=3)

In [60]:
clf.fit(x_train,y_train)

Fitting 5 folds for each of 39 candidates, totalling 195 fits
[CV 1/5] END ...................C=0.1, penalty=l1;, score=nan total time=   0.0s
[CV 2/5] END ...................C=0.1, penalty=l1;, score=nan total time=   0.0s
[CV 3/5] END ...................C=0.1, penalty=l1;, score=nan total time=   0.0s
[CV 4/5] END ...................C=0.1, penalty=l1;, score=nan total time=   0.0s
[CV 5/5] END ...................C=0.1, penalty=l1;, score=nan total time=   0.0s
[CV 1/5] END .................C=0.1, penalty=l2;, score=0.856 total time=   0.0s
[CV 2/5] END .................C=0.1, penalty=l2;, score=0.756 total time=   0.0s
[CV 3/5] END .................C=0.1, penalty=l2;, score=0.806 total time=   0.0s
[CV 4/5] END .................C=0.1, penalty=l2;, score=0.794 total time=   0.0s
[CV 5/5] END .................C=0.1, penalty=l2;, score=0.806 total time=   0.0s
[CV 1/5] END ...........C=0.1, penalty=elasticnet;, score=nan total time=   0.0s
[CV 2/5] END ...........C=0.1, penalty=elasticn

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.1, 0.2, 0.21211, 0.15, 0.25, 0.3, 1, 2, 3, 4,
                               5, 10, 20],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             verbose=3)

In [61]:
clf.best_estimator_

LogisticRegression(C=0.2)

In [62]:
clf.best_params_

{'C': 0.2, 'penalty': 'l2'}

In [63]:
clf.best_score_

np.float64(0.80625)

In [64]:
y_pred = clf.predict(x_test)
y_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1])

In [65]:
accuracy_score(y_test,y_pred)

0.825

In [66]:
#Randomized Search CV>> for large dataset
from sklearn.model_selection import RandomizedSearchCV
clf = RandomizedSearchCV(estimator=model, param_distributions=params, cv=5, verbose=4, n_iter=10)
clf

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [0.1, 0.2, 0.21211, 0.15, 0.25,
                                              0.3, 1, 2, 3, 4, 5, 10, 20],
                                        'penalty': ['l1', 'l2', 'elasticnet']},
                   verbose=4)

In [67]:
clf.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END .....................C=4, penalty=l1;, score=nan total time=   0.0s
[CV 2/5] END .....................C=4, penalty=l1;, score=nan total time=   0.0s
[CV 3/5] END .....................C=4, penalty=l1;, score=nan total time=   0.0s
[CV 4/5] END .....................C=4, penalty=l1;, score=nan total time=   0.0s
[CV 5/5] END .....................C=4, penalty=l1;, score=nan total time=   0.0s
[CV 1/5] END ................C=0.15, penalty=l2;, score=0.856 total time=   0.0s
[CV 2/5] END ................C=0.15, penalty=l2;, score=0.762 total time=   0.0s
[CV 3/5] END ................C=0.15, penalty=l2;, score=0.806 total time=   0.0s
[CV 4/5] END ................C=0.15, penalty=l2;, score=0.806 total time=   0.0s
[CV 5/5] END ................C=0.15, penalty=l2;, score=0.800 total time=   0.0s
[CV 1/5] END ............C=10, penalty=elasticnet;, score=nan total time=   0.0s
[CV 2/5] END ............C=10, penalty=elasticne

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [0.1, 0.2, 0.21211, 0.15, 0.25,
                                              0.3, 1, 2, 3, 4, 5, 10, 20],
                                        'penalty': ['l1', 'l2', 'elasticnet']},
                   verbose=4)

In [68]:
clf.best_estimator_

LogisticRegression(C=0.15)

In [69]:
clf.best_score_

np.float64(0.80625)

In [70]:
clf.best_params_

{'penalty': 'l2', 'C': 0.15}