In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings 
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import make_regression
x, y = make_regression(n_samples=1000, n_features=3, noise=3, random_state=1)
x, y

(array([[ 1.45167891,  0.3416886 , -0.12517266],
        [-0.7003985 , -0.20339445,  0.24266944],
        [-0.10646012, -2.79099641, -0.45611756],
        ...,
        [-0.56282904, -1.2514994 ,  1.29857162],
        [-1.16896134, -1.8994631 , -2.5399554 ],
        [ 0.88608992,  0.31897183,  0.26486763]]),
 array([ 1.39904571e+02, -5.73895194e+01, -2.96893724e+02,  7.21170194e+01,
         5.04726714e+01,  1.57200504e+02,  2.04260303e+02,  2.45152715e+01,
        -4.40087255e+02, -1.69425107e+02,  5.28891813e+01,  2.07289193e+02,
        -9.37774659e+01,  9.35903925e+01, -2.96302269e+02,  7.53450451e+01,
        -1.47200527e+02,  1.14678762e+02,  1.23527566e+02, -1.40769533e+02,
        -1.78451948e+02,  1.22263134e+02, -1.79314709e+01, -8.10963909e+01,
        -6.99232689e+01, -1.53279905e+02,  1.92297657e+02,  2.07265941e+01,
        -8.11609653e+01, -9.59671992e+01,  1.55804815e+02, -7.75749150e+01,
        -8.48911930e+01,  8.07143772e+01,  2.37712896e+02, -2.38146151e+02,
       

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)
x_train.shape, x_test.shape

((700, 3), (300, 3))

In [4]:
from sklearn.neighbors import KNeighborsRegressor
reg = KNeighborsRegressor()
reg.fit(x_train, y_train)
y_pred = reg.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.969184658609626

In [6]:
from sklearn.model_selection import GridSearchCV
params = {
    'n_neighbors' : [1,2,3,5,10,20,30],
    'algorithm' : ['ball_tree','kd_tree','brute'],
    'leaf_size' : [20,3,0,40,50,1,5]
}
grid = GridSearchCV(estimator=reg, param_grid=params, cv=5, verbose=3)
grid.fit(x_train,y_train)
print("BEST PARAMS: ",grid.best_params_)
print("BEST SCORE: ",grid.best_score_)
model = grid.best_estimator_
y_pred = model.predict(x_test)
print(r2_score(y_test, y_pred))

Fitting 5 folds for each of 147 candidates, totalling 735 fits
[CV 1/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=1;, score=0.947 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=1;, score=0.951 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=1;, score=0.957 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=1;, score=0.957 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=1;, score=0.960 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=2;, score=0.963 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=2;, score=0.970 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=2;, score=0.966 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=2;, score=0.975 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=2;, score=0.965 total 

In [7]:
#KNN as missing value treatment
from sklearn.impute import KNNImputer
x = [[1,2,np.nan],[3,4,5],[np.nan,6,5],[8,8,7]]
x

[[1, 2, nan], [3, 4, 5], [nan, 6, 5], [8, 8, 7]]

In [8]:
imputer = KNNImputer(n_neighbors=2)
imputer.fit_transform(x)

array([[1. , 2. , 5. ],
       [3. , 4. , 5. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])