In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings 
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_iris
data = load_iris()
x = data.data
y = data.target
x, y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=1)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
x_train, x_test

(array([[-0.85266944,  0.88903171, -1.29564086, -1.2984507 ],
        [-0.36957061,  1.13127468, -1.40969376, -1.2984507 ],
        [ 2.28747298,  1.8580036 ,  1.66973435,  1.28553079],
        [ 1.32127531,  0.16230279,  0.92839055,  1.15633171],
        [ 1.80437415, -0.32218315,  1.44162857,  0.76873449],
        [ 0.71740177, -0.56442613,  1.04244344,  1.28553079],
        [ 0.47585235, -0.56442613,  0.58623187,  0.76873449],
        [ 0.23430293,  0.88903171,  0.41515253,  0.51033634],
        [ 2.28747298, -0.56442613,  1.66973435,  1.02713264],
        [-0.12802119, -0.07994018,  0.24407319, -0.00645995],
        [-1.21499357,  0.88903171, -1.23861442, -1.2984507 ],
        [-0.12802119, -1.29115505,  0.70028476,  1.02713264],
        [ 0.59662706, -0.8066691 ,  0.64325832,  0.76873449],
        [-1.21499357, -0.07994018, -1.35266731, -1.42764977],
        [-1.33576828,  0.40454576, -1.40969376, -1.2984507 ],
        [ 0.83817648, -0.07994018,  1.15649633,  1.28553079],
        

In [11]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
x_train = pca.fit_transform(x_train)
x_train

array([[-2.13962242,  0.51361087,  0.19941949],
       [-1.99540185,  0.88230113,  0.52959118],
       [ 2.56560809,  2.52456203,  0.33632421],
       [ 1.8817921 ,  0.61359371,  0.09892703],
       [ 2.32153724,  0.26701273,  0.72243786],
       [ 1.84467374, -0.24451667, -0.31650583],
       [ 1.15280787, -0.35008471, -0.10932997],
       [ 0.4790508 ,  0.95287966, -0.36125388],
       [ 2.91219047,  0.19158127,  0.93078197],
       [ 0.08675571, -0.11160955, -0.10833625],
       [-2.30153266,  0.41060989, -0.07682428],
       [ 1.1891939 , -1.19987449, -0.60657463],
       [ 1.30073832, -0.54682835,  0.01597452],
       [-2.24450247, -0.52508153,  0.19211146],
       [-2.36828766, -0.08838333, -0.05808824],
       [ 1.87797779,  0.25405905, -0.32784673],
       [-2.42517095,  0.34914986, -0.32307822],
       [ 1.02242019,  0.07912786, -0.29250815],
       [ 1.39809419,  0.69776328, -0.19862401],
       [ 0.90251119,  0.48222885,  0.56632856],
       [ 0.35933115, -0.56530436, -0.126

In [12]:
# How to decide n_components?
pca.components_

array([[ 0.539189  , -0.20375871,  0.58658648,  0.56892346],
       [ 0.28543082,  0.95620505,  0.00732108,  0.06440146],
       [ 0.74201139, -0.17785208, -0.12967908, -0.63322277]])

In [13]:
pca.explained_variance_ratio_

array([0.71618786, 0.23946458, 0.03982701])

In [14]:
np.cumsum(pca.explained_variance_ratio_)

array([0.71618786, 0.95565244, 0.99547945])

More that 90% variance you got, good to go

So, select 1st two features [0.71, 0.95]

This is deciding of n_vomponents